"""Added more field into role dept

Revision ID: 374bc377ca48
Revises: b83f6dbb9805
Create Date: 2025-07-04 12:26:02.376931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "374bc377ca48"
down_revision: Union[str, Sequence[str], None] = "b83f6dbb9805"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Department", sa.Column("active", sa.Boolean(), nullable=False))
    op.add_column("Department", sa.Column("createdAt", sa.DateTime(), nullable=False))
    op.add_column("Department", sa.Column("updatedAt", sa.DateTime(), nullable=False))
    op.add_column("Role", sa.Column("active", sa.Boolean(), nullable=False))
    op.add_column("Role", sa.Column("createdAt", sa.DateTime(), nullable=False))
    op.add_column("Role", sa.Column("updatedAt", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Role", "updatedAt")
    op.drop_column("Role", "createdAt")
    op.drop_column("Role", "active")
    op.drop_column("Department", "updatedAt")
    op.drop_column("Department", "createdAt")
    op.drop_column("Department", "active")
    # ### end Alembic commands ###
