"""Initial Version

Revision ID: b83f6dbb9805
Revises:
Create Date: 2025-07-02 16:56:19.382042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b83f6dbb9805"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Department",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Department_id"), "Department", ["id"], unique=False)
    op.create_index(op.f("ix_Department_name"), "Department", ["name"], unique=True)
    op.create_table(
        "Role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_Role_id"), "Role", ["id"], unique=False)
    op.create_table(
        "User",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=15), nullable=True),
        sa.Column("firstName", sa.String(length=100), nullable=True),
        sa.Column("lastName", sa.String(length=100), nullable=True),
        sa.Column("dob", sa.Date(), nullable=False),
        sa.Column("doj", sa.Date(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("departmentId", sa.Integer(), nullable=True),
        sa.Column("managerId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["departmentId"], ["Department.id"], name="fk_department_id"
        ),
        sa.ForeignKeyConstraint(["managerId"], ["User.id"], name="fk_user_manager_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_User_id"), "User", ["id"], unique=False)
    op.create_index(op.f("ix_User_phone"), "User", ["phone"], unique=True)
    op.create_table(
        "UserCredential",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashedPassword", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["User.id"],
            name="fk_user_credential_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("userId"),
    )
    op.create_index(
        op.f("ix_UserCredential_email"), "UserCredential", ["email"], unique=True
    )
    op.create_table(
        "UserRole",
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("roleId", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["roleId"], ["Role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("userId", "roleId"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("UserRole")
    op.drop_index(op.f("ix_UserCredential_email"), table_name="UserCredential")
    op.drop_table("UserCredential")
    op.drop_index(op.f("ix_User_phone"), table_name="User")
    op.drop_index(op.f("ix_User_id"), table_name="User")
    op.drop_table("User")
    op.drop_index(op.f("ix_Role_id"), table_name="Role")
    op.drop_table("Role")
    op.drop_index(op.f("ix_Department_name"), table_name="Department")
    op.drop_index(op.f("ix_Department_id"), table_name="Department")
    op.drop_table("Department")
    # ### end Alembic commands ###
